---
- hosts: 172.31.89.142
  become: yes
  tasks:
  - name: uninstall git
    apt:
     name: git
     state: absent
     

  - name: uninstall wget
    apt:
     name: wget
     state: absent
     

  - name: uninstall tree
    apt:
     name: tree
     state: absent  